# Generated by Django 4.2.2 on 2023-11-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='hora',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
