# Generated by Django 4.2.2 on 2023-11-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_historial_hora_alter_historial_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialverificaciones',
            name='tipo',
            field=models.CharField(blank=True, choices=[('venta', 'venta'), ('compra', 'compra'), ('peritaje', 'peritaje')], max_length=50, null=True),
        ),
    ]
