# Generated by Django 4.2.2 on 2023-11-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0005_historial_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='cliente',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
