# Generated by Django 4.2.2 on 2023-11-25 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0006_evento_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='comentarios',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='historial',
            name='operacion',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
