# Generated by Django 4.2.4 on 2024-01-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0007_alter_historial_comentarios_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='nombre_asesor_original',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
