# Generated by Django 4.2.4 on 2024-08-15 00:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0008_lead_nombre_asesor_original"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asesor",
            name="habilitado",
            field=models.BooleanField(default=True),
        ),
    ]
