# Generated by Django 4.2.4 on 2024-08-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboards", "0013_alter_compra_comentario_apertura_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historial",
            name="operacion",
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
