# Generated by Django 4.2.7 on 2024-09-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0015_alter_historial_operacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogomodelo',
            name='years',
            field=models.CharField(default=2024, max_length=255),
            preserve_default=False,
        ),
    ]
