# Generated by Django 4.2.7 on 2024-09-28 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0017_lead_cilindros_lead_kit_conversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiculosintereslead',
            name='cilindros',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculosintereslead',
            name='kit_conversion',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vehiculosintereslead',
            name='tipo_inyeccion',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
