# Generated by Django 4.2.16 on 2024-10-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0018_vehiculosintereslead_cilindros_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='cilindros',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='kit_conversion',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='tipo_inyeccion',
        ),
        migrations.AlterField(
            model_name='catalogorespuestasbyetapa',
            name='etapa',
            field=models.CharField(choices=[('No contactado', 'No contactado'), ('Contactado', 'Contactado'), ('Seguimiento', 'Seguimiento'), ('Anticipo', 'Anticipo'), ('Conversión', 'Conversión'), ('Desistido', 'Desistido')], max_length=50),
        ),
    ]
