# Generated by Django 4.0.5 on 2022-06-14 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seguimientolite_mazda_col", "0002_vistas"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cotizaciones",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("repuesto", models.CharField(blank=True, max_length=250, null=True)),
                ("costo_repuesto", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("costo_mano_obra", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("subtotal", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("monto_iva", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ("total", models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
            ],
            options={
                "db_table": "actividades_cotizaciones",
                "managed": True,
            },
        ),
        migrations.AddField(
            model_name="actividadesasesorfirmas",
            name="tipo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="revisiones",
            name="guia_mantenimiento",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="historialevidencias",
            name="id",
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
