# Generated by Django 4.0.5 on 2022-06-15 03:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientolite_mazda_col', '0003_cotizaciones_actividadesasesorfirmas_tipo_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizaciones',
            options={'managed': True},
        ),
    ]
