# Generated by Django 4.0.5 on 2022-06-28 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientolite_mazda_col', '0004_alter_cotizaciones_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizaciones',
            name='fecha_hora_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='fecha_hora_fin',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='fuente',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='seguimientolite_mazda_col.items'),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='iva',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='cotizaciones',
            name='no_orden',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='loggeneral',
            name='fin_cotizacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loggeneral',
            name='inicio_cotizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
