# Generated by Django 3.2.15 on 2022-09-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientolite_mazda_col', '0005_cotizaciones_fecha_hora_actualizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VRevisionesLimpias',
            fields=[
                ('no_orden', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('verdes', models.IntegerField(blank=True, null=True)),
                ('amarillos', models.IntegerField(blank=True, null=True)),
                ('rojos', models.IntegerField(blank=True, null=True)),
                ('no_aplica', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'v_revisiones_limpias',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='historialevidencias',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='loggeneral',
            name='fin_cotizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='loggeneral',
            name='inicio_cotizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
