# Generated by Django 3.2.15 on 2022-09-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EntrevistaProfesionalAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_hd', models.BigIntegerField(blank=True, null=True)),
                ('no_cita', models.BigIntegerField(blank=True, null=True)),
                ('novedad', models.CharField(blank=True, max_length=200, null=True)),
                ('cuando', models.CharField(blank=True, max_length=200, null=True)),
                ('veces', models.CharField(blank=True, max_length=200, null=True)),
                ('donde', models.CharField(blank=True, max_length=200, null=True)),
                ('accesorios_no_homologados', models.CharField(blank=True, max_length=200, null=True)),
                ('testigos', models.JSONField(blank=True, null=True)),
                ('otro_testigo', models.CharField(blank=True, max_length=200, null=True)),
                ('es_evidente_en_recepcion', models.BooleanField(blank=True, null=True)),
                ('requiere_prueba_de_carretera', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'entrevista_profesional',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ItemsAPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hd', models.BigIntegerField(blank=True, null=True)),
                ('no_orden', models.CharField(blank=True, max_length=25, null=True)),
                ('estado', models.CharField(blank=True, max_length=25, null=True)),
                ('comentarios', models.CharField(blank=True, max_length=500, null=True)),
                ('valor', models.CharField(blank=True, max_length=50, null=True)),
                ('bateria_estado', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('bateria_nivel', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True)),
                ('cambiado', models.BooleanField(default=0)),
                ('tecnico', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_hora_fin', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'actividades_tecnico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ListaItemsAPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('orden', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=250, null=True)),
                ('familia', models.CharField(blank=True, max_length=250, null=True)),
                ('multipuntos', models.BooleanField(blank=True, null=True)),
                ('pagina', models.IntegerField(blank=True, null=True)),
                ('g_x', models.IntegerField(blank=True, null=True)),
                ('g_y', models.IntegerField(blank=True, null=True)),
                ('y_x', models.IntegerField(blank=True, null=True)),
                ('y_y', models.IntegerField(blank=True, null=True)),
                ('r_x', models.IntegerField(blank=True, null=True)),
                ('r_y', models.IntegerField(blank=True, null=True)),
                ('modificado_x', models.IntegerField(blank=True, null=True)),
                ('modificado_y', models.IntegerField(blank=True, null=True)),
                ('valor_x', models.IntegerField(blank=True, null=True)),
                ('valor_y', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'lista_items_tecnico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ManoDeObraAPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hd', models.BigIntegerField(blank=True, null=True)),
                ('no_orden', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad_uts', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('precio_ut', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('porcentaje_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('subtotal_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('fecha_hora_fin', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'actividades_mano_de_obra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RefaccionesAPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('id_hd', models.BigIntegerField(blank=True, null=True)),
                ('no_orden', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(blank=True, max_length=250, null=True)),
                ('no_parte', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('porcentaje_descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('porcentaje_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('subtotal_iva', models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True)),
                ('existencia', models.CharField(blank=True, max_length=10, null=True)),
                ('localizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_hora_fin', models.DateTimeField(auto_now_add=True)),
                ('fecha_hora_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'actividades_refacciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RevisionesAPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=150, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True)),
            ],
            options={
                'db_table': 'lista_revisiones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposCargosAPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'lista_tipos_cargos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposRefaccionesAPI',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'lista_tipos_refacciones',
                'managed': False,
            },
        ),
    ]
