# Generated by Django 4.0.6 on 2022-07-14 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_mazda_col_pro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de documento de identidad',
                'verbose_name_plural': 'Tipos de documento de identidad',
            },
        ),
        migrations.AlterModelOptions(
            name='appointment',
            options={'verbose_name': 'Cita de servicio', 'verbose_name_plural': 'Citas de servicio'},
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Modelo de auto', 'verbose_name_plural': 'Modelos de autos'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Tipo de servicio', 'verbose_name_plural': 'Tipos de servicios'},
        ),
    ]
