# Generated by Django 4.0.6 on 2022-07-14 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas_mazda_col_pro', '0002_documenttype_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carmodel',
            options={'verbose_name': 'Modelo de auto', 'verbose_name_plural': 'Modelos de auto'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name': 'Tipo de servicio', 'verbose_name_plural': 'Tipos de servicio'},
        ),
    ]
