# Generated by Django 4.0.6 on 2022-07-14 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas_mazda_col_pro', '0004_remove_service_service_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceType',
        ),
    ]
