# Generated by Django 4.0.6 on 2022-07-14 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_mazda_col_pro', '0005_delete_servicetype'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='others',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
