# Generated by Django 4.0.6 on 2022-07-20 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas_mazda_col_pro', '0006_service_others'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='additional_service',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='advisor_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='car_condition',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='car_mileage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.carmodel'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='car_model_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_document_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.documenttype'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_email',
            field=models.EmailField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_phone_country_code',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='other_services',
            field=models.ManyToManyField(blank=True, related_name='other_services', to='citas_mazda_col_pro.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.service'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='waiting_room',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='mechanical_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ContactCenter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('license_plate', models.CharField(blank=True, max_length=20, null=True)),
                ('car_model_year', models.IntegerField(blank=True, null=True)),
                ('car_mileage', models.IntegerField(blank=True, null=True)),
                ('client_first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_document_number', models.CharField(blank=True, max_length=20, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=250, null=True)),
                ('client_phone_country_code', models.CharField(blank=True, max_length=3, null=True)),
                ('client_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cancellation_reason', models.IntegerField(blank=True, choices=[('1', 'Otro Servicio'), ('2', 'Novedad/Condición')], null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('car_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.carmodel')),
                ('client_document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.documenttype')),
            ],
            options={
                'verbose_name': 'Contact Center',
                'verbose_name_plural': 'Contact Center',
                'ordering': ['-created_at'],
            },
        ),
    ]
