# Generated by Django 4.0.6 on 2022-07-29 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('citas_mazda_col_pro', '0008_service_service_id_serviceprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCitasUsuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvegrupo', models.IntegerField(db_column='cveGrupo')),
                ('cveperfil', models.IntegerField(db_column='cvePerfil')),
                ('cveusuario', models.CharField(db_column='cveUsuario', max_length=15)),
                ('pass_field', models.CharField(db_column='Pass', max_length=100)),
                ('nombre', models.CharField(blank=True, db_column='Nombre', max_length=150, null=True)),
                ('correoe', models.CharField(blank=True, db_column='correoE', max_length=100, null=True)),
                ('color', models.CharField(blank=True, db_column='Color', max_length=50, null=True)),
                ('cveasesor', models.CharField(blank=True, db_column='cveAsesor', max_length=20, null=True)),
            ],
            options={
                'db_table': 'v_usuarios',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de cita'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='id_hd',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ID HD'),
        ),
        migrations.AddField(
            model_name='contactcenter',
            name='additional_service',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Servicio adicional'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='additional_service',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Servicio adicional'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='advisor_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID del asesor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='car_condition',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Condición del auto'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='car_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraje'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.carmodel', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='car_model_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_document_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.documenttype', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_phone_country_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Código de país'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='other_services',
            field=models.ManyToManyField(blank=True, related_name='other_services', to='citas_mazda_col_pro.service', verbose_name='Otros servicios'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.service', verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='waiting_room',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Espera'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='mechanical_model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo mecánico'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year_end',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de fin'),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='year_start',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de inicio'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='cancellation_reason',
            field=models.IntegerField(blank=True, choices=[('1', 'Otro Servicio'), ('2', 'Novedad/Condición')], null=True, verbose_name='Razón de cancelación'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='car_mileage',
            field=models.IntegerField(blank=True, null=True, verbose_name='Kilometraje'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.carmodel', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='car_model_year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='client_document_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de documento'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='client_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.documenttype', verbose_name='Tipo de documento'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='client_email',
            field=models.EmailField(blank=True, max_length=250, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='client_first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='client_last_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='client_phone_country_code',
            field=models.CharField(blank=True, max_length=3, null=True, verbose_name='Código de país'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='client_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de teléfono'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='contactcenter',
            name='license_plate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Placa'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='service',
            name='active',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='service',
            name='order',
            field=models.IntegerField(blank=True, null=True, verbose_name='Orden'),
        ),
        migrations.AlterField(
            model_name='service',
            name='others',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Otros'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_id',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ID del servicio'),
        ),
        migrations.AlterField(
            model_name='service',
            name='time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo'),
        ),
        migrations.AlterField(
            model_name='service',
            name='wait',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Espera'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='car_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.carmodel', verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=18, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='serviceprice',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='citas_mazda_col_pro.service', verbose_name='Servicio'),
        ),
    ]
